Jfeed22 28 afficher la liste des interventions
btssn-lasalle-84/just-feed-2022 pull request #18
Opened 2022-06-03 08:04 UTC by lmorello

2022-06-03 08:50 UTC, tvaira submitted a review, later dismissed

2022-06-07 11:43 UTC, lmorello commented
Extraction du DeviceID, du port et des données en fonction du numéro de port

2022-06-07 13:09 UTC, tvaira commented
> Extraction du DeviceID, du port et des données en fonction du numéro de port

Pour la suite, il te faut extraire l'objet `decoded_payload` de l'objet `uplink_message` et tu trouveras tes données en fonction du port :

```cpp
QJsonObject messageDonnees = uplink_message.value(QString("decoded_payload")).toObject();

int bac1 = uplink_message.value(QString("bac1")).toInt();
...

emit nouvellesDonneesPortBacs(bac1, bac2);
```

2022-06-07 13:36 UTC, lmorello commented
Je viens d'extraire l'objet decoded_payload de l'objet uplink_message. Cependant, j'ai encore de nombreuses erreurs que je ne parviens pas à résoudre.

2022-06-07 13:36 UTC, tvaira commented on just-feed/communication.cpp
> +    QJsonObject messageDonnees =
A placer avant le `switch`

2022-06-07 13:37 UTC, tvaira commented on just-feed/communication.cpp
> +    emit nouvellesDonneesPortBacs(deviceID, bac1, bac2);
Il faut déclarer les signaux dans `communication.h`

2022-06-08 14:10 UTC, lmorello commented
Ajout des requêtes SQL UPDATE pour chaque bac

2022-06-08 16:16 UTC, tvaira requested changes

2022-06-08 16:16 UTC, tvaira commented on just-feed/communication.cpp
> +            /**
Il faut enlever les TODOs !

2022-06-08 16:16 UTC, tvaira commented on just-feed/ihmjustfeed.cpp
> +    QString requete =
```cpp
QString requete;
bool retour;

requete = "UPDATE StockDistributeur SET quantite=" + QString::number(bac1) + " WHERE idDistributeur=" + idDistributeur + " AND numeroBac=1;";
retour = baseDeDonnees->executer(requete);

requete = "UPDATE StockDistributeur SET quantite=" + QString::number(bac2) + " WHERE idDistributeur=" + idDistributeur + " AND numeroBac=2;";
retour = baseDeDonnees->executer(requete);
```

2022-06-09 13:44 UTC, tvaira approved these changes

2022-06-09 13:44 UTC, merged